### ISSUE TITLE
Can you make different badges for each user?

### ISSUE THREAD

**Issue by siwode1** [danieltj27/verifiedprofiles#8]
I mean can you make a custom badge system I want to add different badges for each user? I was just asking..... xD

**Comment by danieltj27** [comment]
That's sort of out of scope for this extension really. As that would start to creep into a more generic badge system and I definitely wouldn't do that in a free extension. If I get time I could certainly consider it for a premium version of the extension though.

**Comment by siwode1** [comment]
ok ^^
